name: 'Setup Java, build tool and install dependencies'
description: 'Setup Java SDK, the build tool, fetch and cache packages dependencies'

inputs:
  working-directory:
    description: 'The working directory'
    default: '.'
  java-version:
    default: '21'
    description: 'Java Version'
  distribution:
    default: 'corretto'
    description: 'Java Distribution'
  build-tool:
    default: 'Maven'
    description: 'The build tool to use. The options `Maven` and `Gradle` are supported'
  cache:
    default: 'true'
    description: 'Enable Maven/Gradle dependency caching.'
  cache-name:
    default: 'aboutbits-setup-java'
    description: 'Maven cache name. Caches with the same name will share their contents. This is not applicable to Gradle as `gradle/actions/setup-gradle` manages caching for us.'

outputs:
  distribution:
    description: 'Distribution of Java that has been installed.'
    value: ${{ steps.setup-java.outputs.distribution }}
  version:
    description: 'Actual version of the java environment that has been installed.'
    value: ${{ steps.setup-java.outputs.version }}
  path:
    description: 'Path to where the java environment has been installed (same as $JAVA_HOME).'
    value: ${{ steps.setup-java.outputs.path }}
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key.'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      id: setup-java
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}

    - name: Cache local Maven repository
      uses: actions/cache@v4
      id: cache
      if: ${{ inputs.cache == 'true' && inputs.build-tool == 'Maven' }}
      with:
        path: ~/.m2/repository
        key: ${{ inputs.cache-name }}-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ inputs.cache-name }}-${{ runner.os }}-maven-

    - name: Update Maven dependencies
      working-directory: ${{ inputs.working-directory }}
      if: ${{ inputs.build-tool == 'Maven' }}
      run: ./mvnw --batch-mode --fail-fast dependency:resolve dependency:resolve-plugins
      shell: bash

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      if: ${{ inputs.build-tool == 'Gradle' }}
      with:
        cache-disabled: ${{ inputs.cache == 'false' }}
        cache-read-only: 'false'

    - name: Update project configuration and Gradle dependencies
      working-directory: ${{ inputs.working-directory }}
      if: ${{ inputs.build-tool == 'Gradle' }}
      run: ./gradlew build --dry-run
      shell: bash
