name: 'Setup Java and install dependencies'
description: 'Setup Java SDK, fetch and cache packages dependencies'

inputs:
  working-directory:
    description: 'The working directory'
    default: '.'
  java-version:
    description: 'Java Version'
    default: '21'
  distribution:
    description: 'Java Distribution'
    default: 'corretto'
  cache:
    description: 'Enable Maven dependency caching.'
    default: 'true'
  cache-name:
    description: 'Cache name. Caches with the same name will share their contents.'
    default: 'aboutbits-setup-java'

outputs:
  path:
    description: 'Path to where the java environment has been installed (same as $JAVA_HOME).'
    value: ${{ steps.setup-java.outputs.path }}
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key.'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      id: setup-java
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
    - name: Cache local Maven repository
      uses: actions/cache@v4
      id: cache
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ~/.m2/repository
        key: ${{ inputs.cache-name }}-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ inputs.cache-name }}-${{ runner.os }}-maven-
    - name: Update Maven dependencies
      working-directory: ${{ inputs.working-directory }}
      run: ./mvnw --batch-mode --fail-fast dependency:resolve dependency:resolve-plugins
      shell: bash
